[theme]
primaryColor = "#0b8f62"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f5f7"
textColor = "#15202b"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
